TASK-35704: Create FB maintenance and update projects versions/dependencies
Meeds-io/perk-store pull request #111
Opened 2021-08-30 13:42 UTC by SaraBoutej

When clicking on perk-store order widget on snapshot page, My command view should be opened!

2021-08-30 13:45 UTC, azayati commented
@SaraBoutej I think that the PR title is not good

2021-08-31 07:01 UTC, rdenarie requested changes
Hello Sara,

Can you update your PR description to follow the commit message best practises : https://developer.exoplatform.org/#id-commits-messages-best-practices

Your description should be on format 
<title>
<empty line>
<description answering WHY ? and HOW ? questions>

In addition, can put the PR description in the commit message ?

Thanks

2021-08-31 12:00 UTC, SaraBoutej commented
> Can you update your PR description to follow the commit message best practises : https://developer.exoplatform.org/#id-commits-messages-best-practices

> In addition, can put the PR description in the commit message ?

done @rdenarie

2021-08-31 12:33 UTC, rdenarie requested changes
You update the PR description with a correct message. Can you now update the commit message ?
Thanks

2021-08-31 13:20 UTC, SaraBoutej commented
> You update the PR description with a correct message. Can you now update the commit message ?
> Thanks

done @rdenarie

2021-08-31 13:43 UTC, rdenarie approved these changes

2021-08-31 13:47 UTC, merged