TASK-49420 : Mobile UI in perkstore
Meeds-io/perk-store pull request #120
Opened 2021-09-29 15:59 UTC by GouadriaHanen

2021-09-29 16:17 UTC, Rdidmohamedelhadi requested changes
Preferably we use the predefined classes of vuetify for padding and margin

link : https://vuetifyjs.com/en/styles/spacing/#how-it-works

2021-09-29 16:17 UTC, Rdidmohamedelhadi commented on perk-store-webapps/src/main/webapp/css/main.less
> +        padding: 15px 5px 15px 15px;
You can use pa-4 directly (https://vuetifyjs.com/en/styles/spacing/#how-it-works)

2021-09-29 16:17 UTC, Rdidmohamedelhadi commented on perk-store-webapps/src/main/webapp/css/main.less
> +        padding: 15px 5px 15px 15px;
the same remark for this line

2021-09-29 16:17 UTC, Rdidmohamedelhadi commented on perk-store-webapps/src/main/webapp/css/main.less
> +@media (max-width : @smallMobileWidth){
it should not be changed

2021-09-30 13:31 UTC, Rdidmohamedelhadi requested changes

2021-09-30 13:31 UTC, Rdidmohamedelhadi commented on perk-store-webapps/src/main/webapp/css/main.less
> +            margin-top: 15px;
change this please to mt-4

2021-09-30 13:31 UTC, Rdidmohamedelhadi commented on perk-store-webapps/src/main/webapp/css/main.less
> +            margin-top: 15px;
margin-top: 15px ==> mt-4

2021-09-30 13:31 UTC, Rdidmohamedelhadi commented on perk-store-webapps/src/main/webapp/css/main.less
> +            margin-top: 12px;
margin-top: 12px; ==> mt-3

2021-09-30 13:31 UTC, Rdidmohamedelhadi commented on perk-store-webapps/src/main/webapp/css/main.less
> +            margin-top: 15px;
same for this line

2021-10-01 15:13 UTC, GouadriaHanen commented
@Rdidmohamedelhadi   they all depend on the media width!

2021-10-01 15:42 UTC, Rdidmohamedelhadi commented
> @Rdidmohamedelhadi they all depend on the media width!

for this margin-top: 12px; you can use mt-3 (https://vuetifyjs.com/en/styles/spacing/#how-it-works)

2021-10-01 16:31 UTC, Rdidmohamedelhadi commented
> @Rdidmohamedelhadi they all depend on the media width!

aaah ok !

2021-10-01 16:31 UTC, Rdidmohamedelhadi approved these changes
LGTM

2021-10-01 16:33 UTC, merged