Task 49870 : Add perk store admin into side bar
Meeds-io/perk-store pull request #125
Opened 2021-10-08 13:30 UTC by Rdidmohamedelhadi

I added the navigation for the perk store admin. I added this into side bar under reword.

2021-10-13 16:25 UTC, GouadriaHanen approved these changes
LGTM

2021-10-14 10:14 UTC, ahamdi approved these changes

2021-10-14 10:15 UTC, ahamdi requested changes
Could you fix SONAR review bugs

2021-10-14 11:28 UTC, Rdidmohamedelhadi commented
> Could you fix SONAR review bugs

done !!

2021-10-14 19:03 UTC, ahamdi approved these changes

2021-10-14 22:19 UTC, merged