TASK-55140: display alert when metamask network is not Polygon network
Meeds-io/perk-store pull request #161
Opened 2022-04-25 11:22 UTC by GouadriaHanen

display Erroneous network alert when metamask network is not Polygon network

2022-04-25 11:36 UTC, ahamdi approved these changes

2022-04-25 11:36 UTC, ahamdi commented on perk-store-webapps/src/main/webapp/vue-app/components/perk-store/BuyModal.vue
> +      polygonURL: 'https://polygon.technology'
do not hardcode network, this should be retrieved from configuration.
Using the networkID, you can get which network is activated like in https://github.com/meeds-io/wallet/blob/develop/wallet-webapps-common/src/main/webapp/vue-app/js/WalletUtils.js#L299

2022-04-25 11:37 UTC, ahamdi requested changes
Please consider my comment

2022-04-25 12:19 UTC, GouadriaHanen commented
related to this PR : https://github.com/Meeds-io/wallet/pull/226

2022-04-26 10:59 UTC, ahamdi approved these changes

2022-04-26 11:01 UTC, merged